# http://www.appveyor.com/docs/appveyor-yml

# version format
version: 2.0.{build}

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# scripts that run after cloning repository
install:
  - ps: .\build.ps1

# to disable automatic builds
build: off
