# http://www.appveyor.com/docs/appveyor-yml

# version format
version: 1.0.{build}

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\myproject

# scripts that run after cloning repository
install:
  - ps: .\build.ps1

# to disable automatic builds
build: off
