# http://www.appveyor.com/docs/appveyor-yml

# version format
version: 1.0.{build}

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\myproject

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - echo This is batch
  - build.bat
  # to run script as a PowerShell command prepend it with ps:
  - ps: Write-Host 'This is PowerShell'
  # batch commands start from cmd:
  - cmd: echo This is batch again
  - cmd: set MY_VAR=12345



# to disable automatic builds
#build: off


# to disable deployment
#deploy: off
